import 'dart:io';

String EMAIL='';
String JOINCURRENTCHANNEL='';
String HOSTCURRENTCHANNEL='';
late String NAME;
late String COUNTRY;
String DATE="Not Selected";
bool RANDOMCALL=false;
String LOCATION="Not Selected";
String JOB="Not Selected";
String DESCRIBE="Not Selected";
String EDUCATION="Not Selected";
late String PHONE;
late String GENDER;
late File PHOTO;
String MARITAL='Not Selected';
String DRINKING="Not Selected";
String SMOKING="Not Selected";
String EATING="Not Selected";
String PERSONALITY="Not Selected";
late List INTERESTS;
late List ModifyINTERESTS;
late String UID;
bool IMAGESELECTED=false;
//'https://www.kindpng.com/picc/m/252-2524695_dummy-profile-image-jpg-hd-png-download.png';
