name: look
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"
dependencies:
  agora_rtc_engine: ^5.2.0
  cloud_firestore: ^3.1.0
  country_code_picker: ^2.0.2
  cupertino_icons: ^1.0.2
  custom_switch: ^0.0.1-nullsafety.0
  date_time_picker: ^2.1.0
  firebase: ^9.0.2
  firebase_auth: ^3.2.0
  firebase_core: ^1.10.0
  firebase_storage: ^10.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  geocode: 1.0.1
  geolocator: ^8.0.0
  get: ^4.3.8
  google_maps_flutter: ^2.1.1
  google_sign_in: ^5.2.1
  image_picker: ^0.8.4+4
  intl_utils: ^2.6.1
  location: ^4.2.0
  mvc_pattern: ^8.10.1+1
  permission_handler: ^8.2.0
  pin_code_fields: ^7.4.0
  url_launcher: ^6.0.17
  webview_flutter: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: PopM
      fonts:
        - asset: assets/font/Poppins-Medium.ttf

flutter_intl:
  enabled: true
