const String logo = 'assets/look8.png';
const String callhistory = 'assets/callhistory.png';
const String publicnotice = 'assets/publicnotice.png';
const String transhistory = 'assets/transhistory.png';
const String settings = 'assets/settings.png';
const String personal = 'assets/personal.png';
const String inquiry = 'assets/inquiry.png';
const String chats = 'assets/chats.png';
const String user = 'assets/user.png';
const String search = 'assets/search.png';
const String random = 'assets/random.png';
const String loading = 'assets/loading.gif';
const String location = 'assets/location.png';
const String invitee = 'assets/invitee.png';
const String coinstore = 'assets/coinstore.png';
const String terms = 'assets/terms.png';
const String edit = "assets/edit.PNG";
const String daimond = 'assets/diamond.png';
const String directions = 'assets/direction.png';
const String grid = 'assets/grid.png';
const String list = 'assets/list.png';
const String box = 'assets/box.png';
const String award = "assets/award.PNG";
const String english = "assets/en.png";
const String nodatafound = "assets/nodata.png";
const String korean = "assets/ko.png";
const String currency = "₩";
// const String logo = "assets/look8.png";
const String noImage =
    "https://t4.ftcdn.net/jpg/04/70/29/97/240_F_470299797_UD0eoVMMSUbHCcNJCdv2t8B2g1GVqYgs.jpg";

///Icons///
const String rainbow = "assets/icons/rainbow.png";
const String party = "assets/icons/party.png";
const String in_love = "assets/icons/in_love.png";
const String heart = "assets/icons/heart.png";
const String fire = "assets/icons/fire.png";
const String emoji = "assets/icons/emoji.png";
const String confetti = "assets/icons/confetti.png";
